server:
  port: 8888
spring:
  application:
    name: proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/

#zuul:
#    routes:
#        userApi:
#            path: /home/**
#            stripPrefix: false
#            serviceId: user