server:
  port: 8761
spring:
  application:
    name: registry
security:
  basic:
    enabled: true
  user:
    name: username
    password: password
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://username:password@localhost:${server.port}/eureka/